### PR TITLE
fix: authorize upload error on create job endpoint

### LINKED ISSUE #1632: Feed generates error to authorize upload
### Describe the bug

When using the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, it generates an "Error authorizing upload". 

### Steps/Code to Reproduce

- Go to Web UI 
- Input https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000 in "Or load from a URL" field 
- Validate feed 
- Generate "Error authorizing upload" error

### Expected Results

Feed generates report successfully. 

### Actual Results

Screenshot 2023-12-19 at 5 58 48 AM

### Screenshots

_No response_

### Files used

_No response_

### Validator version

4.2.0 

### Operating system

MacOS

### Java version

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by davidgamez**
**Summary:**

When utilizing the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, an "Error authorizing upload" occurs. Upon attempting to save the file to GCP for validation, it was observed that the HTTP request lacked a user-agent, leading to rejection by the producer in this specific instance.

This is a missing fix from #1633. 
Fixes #1632

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/util/StorageHelper.java [hunk 1]
```diff
@@ -101,18 +104,20 @@ public JobMetadata getJobMetadata(String jobId) {
...
-    storage.create(blobInfo, fileBytes);
+  public void saveJobFileFromUrl(String jobId, String url, String validatorVersion)
+      throws Exception {
+    var blobId = BlobId.of(USER_UPLOAD_BUCKET_NAME, jobId + "/" + FILE_NAME);
+    var blobInfo = BlobInfo.newBuilder(blobId).setContentType("application/zip").build();
+    URL signedURL =
+        storage.signUrl(
+            blobInfo, 1, TimeUnit.HOURS, Storage.SignUrlOption.httpMethod(HttpMethod.POST));
+    try (WriteChannel writer = storage.writer(signedURL)) {
+      OutputStream outputStream = Channels.newOutputStream(writer);
```
Comment (davidgamez) [inline web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/util/StorageHelper.java:118]: Using the Channels output stream reduces the memory footprint by avoiding loading the full file in memory.

**Review by jcpitre — APPROVED** [review]
