### PR TITLE
fix: StopZoneIdValidator

### LINKED ISSUE #950: fix: check stops.zone_id presence
This is checking stop or station but the name says "stop or entrance".

1. What do we actually need here?
2. Is that behaviour covered by unit tests?

_Originally posted by @aababilov in https://github.com/MobilityData/gtfs-validator/pull/936#discussion_r685682266_

### PR DESCRIPTION
**Pull request by lionel-nj**
closes #950

**Summary:**

This PR provides support to check `STATION` or `ENTRANCE` in `StopZoneIdValidator`.

**Expected behavior:** 

No notice should be generated for a record from `stops.txt` if `stop.zone_id` is empty AND `stops.location_type=1` or `stops.location_type=2`

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ public void validate(NoticeContainer noticeContainer) {
 
   private boolean isStationOrEntrance(GtfsStop stop) {
     return stop.locationType().equals(GtfsLocationType.STATION)
-        || stop.locationType().equals(GtfsLocationType.STOP);
+        || stop.locationType().equals(GtfsLocationType.ENTRANCE);
```
Comment (aababilov) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java:67]: Let's discuss that together. Do we need to show a notice if a generic node or a boarding area does not have zone_id? My feeling is that we don't need it. What do you think?

Comment (isabelle-dr) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java:67]: We don't need a warning in the case of boarding areas and zone_id, the spec says:

> | zone_id | ID | Conditionally Required | Identifies the fare zone for a stop. If this record represents a station or station entrance, the zone_id is ignored.

**Review by isabelle-dr — APPROVED** [review]

File: RULES.md [hunk 2]
```diff
@@ -848,7 +848,7 @@ Such stops normally do not provide user value. This notice may indicate a typo i
 
 #### StopWithoutZoneIdNotice
 
-Per GTFS specification, `stops.zone_id` should be provided if fare information is provided using `fare_rules.txt`. This rule does not apply to records from `stops.txt` that represent a stop or en entrance (i.e. `stops.location_type = 1 or 2`).
+Per GTFS specification, `stops.zone_id` should be provided if fare information is provided using `fare_rules.txt`. This rule does not apply to records from `stops.txt` that represent a station or en entrance (i.e. `stops.location_type = 1 or 2`).
```
Comment (aababilov) [inline RULES.md:851]: "a station or en entrance" has a typo (en entrance) and looks outdated.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java (hunk 1 above)
Comment (aababilov) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java:67]: Great, then we need to update this code (including function name) and unit tests.

File: main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java [hunk 3]
```diff
@@ -74,8 +74,19 @@ public void emptyFareRuleZoneId_noNotice() {
     assertThat(
             generateNotices(
                 ImmutableList.of(
+                    createStop(4, GtfsLocationType.STOP, "zone id value", "stop id value"),
```
Comment (aababilov) [inline main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java:77]: For the whole file: please write one unit test per (location type, presence of zone_id). This will give you 5 * 2 = 10 tests.

**Review by aababilov — CHANGES_REQUESTED** [review]

File: main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java (hunk 3 above)
Comment (lionel-nj) [reply main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java]: Addressed in https://github.com/MobilityData/gtfs-validator/pull/972/commits/f836516e35f3f3bc711683039a1bff7930477bf9.

File: RULES.md (hunk 2 above)
Comment (lionel-nj) [reply RULES.md]: Thanks, fixed in https://github.com/MobilityData/gtfs-validator/pull/972/commits/9789068e732890bc5eede91e2ca82dcd574d5cf0 and https://github.com/MobilityData/gtfs-validator/pull/972/commits/f836516e35f3f3bc711683039a1bff7930477bf9.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java (hunk 1 above)
Comment (aababilov) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java]: This still emits warnings for boarding areas without zone_id (and it is covered by unit tests).

I think what we need is just to emit the warning for location_type=stop. So, you do not actually need the function - you may just inline the condition for clarity.
```
for (GtfsStop stop : stopTable.getEntities()) {
    if (stop.locationType().equals(GtfsLocationType.STOP) && !stop.hasZoneId()) {
        noticeContainer.addValidationNotice(
            new StopWithoutZoneIdNotice(stop.stopId(), stop.csvRowNumber()));
    }
}
```

**Review by aababilov — CHANGES_REQUESTED** [review]
I also recommend to add stopName field to the notice and pass GtfsStop as a parameter for convenience.

Honestly, I wonder why GTFS standard has this requirement this way. Why can't zone_id be provided for a station and apply to all child platforms? However, Google implementation agrees with the official GTFS description.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java (hunk 1 above)
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java]: My bad I missed the case for boarding areas. Fixed in https://github.com/MobilityData/gtfs-validator/pull/972/commits/20ee0037b46b70ed44d0655668c4e6314df5964b. Thanks for flagging that.

**Review by aababilov — APPROVED** [review]
LGTM, just one minor remark. Thanks a lot!

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java [hunk 4]
```diff
@@ -51,22 +50,12 @@ public void validate(NoticeContainer noticeContainer) {
       return;
     }
     for (GtfsStop stop : stopTable.getEntities()) {
-      if (isStationOrEntrance(stop)) {
-        return;
+      if (stop.locationType().equals(GtfsLocationType.STOP) && !stop.hasZoneId()) {
+        noticeContainer.addValidationNotice(new StopWithoutZoneIdNotice(stop, stop.csvRowNumber()));
```
[the remark this answers is not in the document]
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java]: Addressed in https://github.com/MobilityData/gtfs-validator/pull/972/commits/18c79215114536117b748e87c9c9b8288f068cc8.

**Comment by lionel-nj** [comment]
Thanks for reviewing @aababilov!
