### PR TITLE
fix: update TripAndShapeDistanceValidator to ignore shape with no shape_dist_traveled (#2018)

### LINKED ISSUE #2018: trip_distance_exceeds_shape_distance: do not trigger when shapes.shape_dist_traveled column is empty
### Describe the problem

Example feed: https://mobilitydatabase.org/feeds/gtfs/mdb-2458 

Right now, when a trip has a shape_dist_traveled value in stop_times.txt but its associated shape has no shape_dist_traveled value in shapes.txt, the trip_distance_exceeds_shape_distance error is triggered. This should not happen.

### Proposed solution

- Review why this is happening (why do we interpret shapes.shape_dist_traveled value as 0 when the column doesn't exist in shapes.txt?) 
- Modify behavior
- Test with feed to ensure the error no longer triggers
- Additional request: modify notice description to include: 

"A stop time's shape_dist_traveled exceeds the maximum shape_dist_traveled of the shape for the related trip in shapes.txt." 

And references: https://gtfs.org/documentation/schedule/reference/#stop_timestxt

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thelleboid-tsr**
**Summary:**
update TripAndShapeDistanceValidator to ignore shape with no shape_dist_traveled

**Expected behavior:** 

Some GTFS feeds do not provide shape_dist_traveled in shapes.txt In this case, the value is set to 0 in the code, so sorting shapes based on ShapeDistTraveled does not work and usually returns the first shape row.

It leads to an error, the first shape of the shape is usually very far away from the last stop of the trips following the shape.

We can assume the biggest shape_dist_traveled of a given shape should never be 0, otherwise it means the value is not set. In this case, we return early to ensure no validation error will be issued.

Fixes #2018

⚠️ I've not been able to run unit tests on this PR

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java [hunk 1]
```diff
@@ -40,7 +40,7 @@ private static List<GtfsShape> createShapeTable(
               .setShapePtLat(lonLat)
               .setShapePtLon(lonLat)
               .setShapePtSequence(0)
-              .setShapeDistTraveled(shapeDistTraveled + i)
+              .setShapeDistTraveled(shapeDistTraveled * i)
```
Comment (jcpitre) [inline main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java:43]: Thanks for the contribution!
Why this change?
It makes some tests fail:

[TripAndShapeDistanceValidatorTest.testTripDistanceExceedsShapeDistance](https://github.com/MobilityData/gtfs-validator/blob/f1174bd08ed57366ef8a54fe360f89543b5beecd/main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java#L94)
[TripAndShapeDistanceValidatorTest.testTripDistanceExceedsShapeDistanceWarning](https://github.com/MobilityData/gtfs-validator/blob/f1174bd08ed57366ef8a54fe360f89543b5beecd/main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java#L112)

Your test will work if you keep the line as is (i.e +1), since you set `shapeDistTraveled` to 0 when calling `createShapeTable` and only one row is created.

You can run the tests locally with:
`./gradlew test`

File: main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java [hunk 2]
```diff
@@ -108,6 +108,24 @@ public void testTripDistanceExceedsShapeDistance() {
     assertThat(found).isTrue();
   }
 
+  @Test
+  public void testTripDistanceExceedsShapeDistanceNoShapeDistance() {
+    List<ValidationNotice> notices =
+        generateNotices(
+            createTripTable(2),
+            createStopTimesTable(1, 10.0),
```
Comment (jcpitre) [inline main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java:116]: I think this will not really test your change. You want to set test data that would normally create a notice but will not because shapeTable.shapeDistTraveled is 0 (please correct me if I am wrong).
But to generate a notice you need the distance to be at least 11.1 meters. And this test sets the distance to 10 meters. So the test as it is now will not generate notices, because the distance falls below the threshold.

I believe that if you set `createStopTimesTable(1, 100.0)` (for example), it will test properly.

**Comment by skalexch** [comment]
@thelleboid-tsr I don't see a problem spec-wise. Once you're able to generate acceptance tests, I can take a look at the data and notices.

**Comment by emmambd** [comment]
Hi @skalexch! @thelleboid-tsr already generated the acceptance tests at https://github.com/MobilityData/gtfs-validator/actions/runs/14531693839 so we can review them there. [There's a separate issue for generating a comment when the acceptance test is created from forked PRs. ](https://github.com/MobilityData/gtfs-validator/issues/1960).

**Review by skalexch — COMMENTED** [review]
@emmambd thank you. @thelleboid-tsr looking at the datasets, it seems like the error is dropped for both feeds that do not have the column (eg mdb-67) and feeds that have the field but it's empty (eg mdb-1270). All good spec-wise! I'll leave the approval for dev.

**Review by jcpitre — APPROVED** [review]
LGTM!
The increased number of corrupted feeds is not related to this PR.
