### PR TITLE
fix: 1707 web validator waits for validation forever

### LINKED ISSUE #1707: Web validator waits for validation forever
### Describe the bug

Trying validation on a uploaded dataset hangs forever with this window:
image

This is intermittent

### Steps/Code to Reproduce

Upload a dataset to the validator and try to validate.
It's intermittent, and does not happen very often.

### Expected Results

A window directing to the validation report

### Actual Results

See above

### Screenshots

image

### Files used

_No response_

### Validator version

4.2.0

### Operating system

irrelevant

### Java version

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by jcpitre**
**Summary:**

Closes #1707 

If there is no timeout on the version endpoint, this PR changes nothing.
Changed the code so it does not generate an exception when the version endpoint is called but times out.
Another problem was that the current version (obtained from the jar files) was discarded if there was a time out calling the version endpoint. 

**Expected behavior:** 

Web validator does not hang forever if there is a timeout while calling the version endpoint.
If the timeout happens, the version is still correct in report.html

** Testing tips **

The timeout is intermittent, and probably only occurs when the validator service is brought up.
To test this, you could add a delay in  [VersionResolver.java](https://github.com/MobilityData/gtfs-validator/blob/dee5802afc2f0e37b0299a5d6dca192c08ee4af8/main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java#L150), e.g.  Thread.sleep(5100) to simulate that the endpoint takes a long time to respond. The delay should be above 5000 ms, since it's the time used for the timeout.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java [hunk 1]
```diff
@@ -153,7 +166,7 @@ private Optional<String> resolveLatestReleaseVersion(Optional<String> currentVer
         new URL(
             String.format(
                 "%s?application_type=%s&current_version=%s",
-                LATEST_RELEASE_VERSION_URL, applicationType, currentVersion.orElse("Ï")));
```
Comment (jcpitre) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java:156]: I don't know why this character `"Ï"` was there.

**Review by davidgamez — APPROVED** [review]
LGTM!
