### PR TITLE
fix: Display empty values for feed_start_date and feed_end_date if there's…

### LINKED ISSUE #1790: Validation report summary shows Unix time 0 for feed_start_date and feed_end_date when feed_info.txt exists with empty date values
### Describe the problem

Feed example: https://s3.amazonaws.com/datatools-511ny/public/PART_Putnam_Area_Rapid_Transit.zip 

This feed doesn't include feed_info.txt and has calendar dates that are active. However, [the feed summary report](https://gtfs-validator-results.mobilitydata.org/1d7cc8de-76ff-45c9-9fd2-986cfbef75c2/report.html) includes the feed_start_date and feed_end_date as 1970-01-01 when it should just be empty values. 

### Proposed solution

feed_start_date and feed_end_date should be empty in the summary report when feed_info exists but feed_start_date and feed_end_date are empty - not default to Unix time 0.

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**
Closes #1790 
image

**Expected behavior:** 

Display empty values for feed_start_date and feed_end_date if there's no data for these two fields.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by emmambd** [comment]
@qcdyx Looks good on a QA side! Minor change: can we display "N/A" instead of an empty value? I realized it should match the other null behavior in the summary report (e.g agency email and URL, where if they're empty it returns N/A)

File: main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java [hunk 1]
```diff
@@ -309,14 +310,14 @@ private void loadFeedInfo(GtfsTableContainer<GtfsFeedInfo> feedTable) {
     feedInfo.put(
         FEED_INFO_FEED_LANGUAGE, info == null ? "N/A" : info.feedLang().getDisplayLanguage());
     if (feedTable.hasColumn(GtfsFeedInfo.FEED_START_DATE_FIELD_NAME)) {
-      feedInfo.put(
-          FEED_INFO_FEED_START_DATE,
-          info == null ? "N/A" : info.feedStartDate().getLocalDate().toString());
+      LocalDate localDate = info.feedStartDate().getLocalDate();
+      String displayDate = localDate.equals(LocalDate.of(1970, 1, 1)) ? "N/A" : localDate.toString();
+      feedInfo.put(FEED_INFO_FEED_START_DATE, info == null ? "N/A" : displayDate);
```
Comment (davidgamez) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java]: The `N/A` should be rendered in the HTML file. Having the `N\A` in the feedInfo instance will replicate the value in the JSON file. This leads to issues on the consumer side when parsing a valid date. We have an example in the email of an invalid value being put in the JSON file, an example of a JSON report. https://gtfs-validator-results.mobilitydata.org/4a1ab20a-5e9e-47fb-8b86-45bc60e88b3f/report.json

File: main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java [hunk 2]
```diff
@@ -309,14 +310,16 @@ private void loadFeedInfo(GtfsTableContainer<GtfsFeedInfo> feedTable) {
     feedInfo.put(
         FEED_INFO_FEED_LANGUAGE, info == null ? "N/A" : info.feedLang().getDisplayLanguage());
     if (feedTable.hasColumn(GtfsFeedInfo.FEED_START_DATE_FIELD_NAME)) {
-      feedInfo.put(
-          FEED_INFO_FEED_START_DATE,
-          info == null ? "N/A" : info.feedStartDate().getLocalDate().toString());
+      LocalDate localDate = info.feedStartDate().getLocalDate();
+      String displayDate =
+          localDate.equals(LocalDate.of(1970, 1, 1)) ? "N/A" : localDate.toString();
```
Comment (davidgamez) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java:315]: Let's use the default feed start date set by the Gtfs entity => GtfsFeedInfo.DEFAULT_FEED_START_DATE instead of the LocalDate.of(1970, 1, 1). It is technically the same, but _if_ the default date is changed, this code will likely be left behind.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java [hunk 3]
```diff
@@ -309,14 +310,16 @@ private void loadFeedInfo(GtfsTableContainer<GtfsFeedInfo> feedTable) {
...
+      feedInfo.put(FEED_INFO_FEED_START_DATE, info == null ? "N/A" : displayDate);
     }
     if (feedTable.hasColumn(GtfsFeedInfo.FEED_END_DATE_FIELD_NAME)) {
-      feedInfo.put(
-          FEED_INFO_FEED_END_DATE,
-          info == null ? "N/A" : info.feedEndDate().getLocalDate().toString());
+      LocalDate localDate = info.feedEndDate().getLocalDate();
+      String displayDate =
+          localDate.equals(LocalDate.of(1970, 1, 1)) ? "N/A" : localDate.toString();
```
Comment (davidgamez) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java:321]: Same comment as before => Let's use the default feed end date set by the Gtfs entity => GtfsFeedInfo.DEFAULT_FEED_END_DATE instead of the LocalDate.of(1970, 1, 1). It is technically the same, but _if_ the default date is changed, this code will likely be left behind.

**Review by davidgamez — APPROVED** [review]
