### PR TITLE
fix: add system errors to notice container

### LINKED ISSUE #548: Provide information about system errors
This is a great question. I would suggest to generate a separate report for system errors (IO error, out of memory, exception raised in a validation etc). 

Rationale.
------------
1. Program that runs the validator needs to know why it crashed and a JSON report is more convenient than parsing stdout.
2. There may be bugs in individual validations and we need information about them.
3. We should not leak information about system errors to clients, so system errors should not be placed to the same report as validation errors.

Implementation
--------------------
We can have a special subclass of `Notice` (`SystemError`). NoticeContainer called on SystemError should keep it in a separate place.

_Originally posted by @aababilov in https://github.com/MobilityData/gtfs-validator/pull/541#discussion_r539004969_

### PR DESCRIPTION
**Pull request by lionel-nj**
closes #548

Duplicated #602

**Summary:**

https://github.com/MobilityData/gtfs-validator/pull/596 introduced the concept of system errors. 
Those need to be added to the noticeContainer in the main method. 
This PR suggests code to proceed.

**Expected behavior:** 

1. System errors should be added to the notice container
2. Reports should be generated and exported.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: -new feature short description-" (PR title must follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] Linked all relevant issues
- ~[] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 1]
```diff
@@ -75,29 +77,37 @@ public static void main(String[] argv) {
...
+    final long endNanos = System.nanoTime();
+    System.out.printf("Validation took %.3f seconds%n", (endNanos - startNanos) / 1e9);
+    System.out.println(feedContainer.tableTotals());
+  }
 
-    // Output.
+  /**
+   * Generates and exports reports for both validation notices and system errors reports
+   */
+  private static void generateAndExportReports(
```
Comment (barbeau) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:99]: Nit: maybe shorter name `exportReports()`?

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 2]
```diff
@@ -75,29 +77,37 @@ public static void main(String[] argv) {
...
+          final Arguments args, final NoticeContainer noticeContainer) {
```
Comment (barbeau) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:100]: If output base is the only variable of Arguments used, maybe just pass that instead of the entire Arguments object instead?

**Review by barbeau — COMMENTED** [review]
Thanks @lionel-nj, this mostly looks good to me - a few comments in-line.

Given that @aababilov implemented https://github.com/MobilityData/gtfs-validator/pull/596 I'd like to get his comments as well.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java (hunk 2 above)
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:100]: Indeed! Thanks.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/GtfsInputCreationError.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.mobilitydata.gtfsvalidator.notice;
+
+import com.google.common.collect.ImmutableMap;
+
+/**
+ * Describes a runtime exception while creating a @code{GtfsInput}
```
Comment (aababilov) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/notice/GtfsInputCreationError.java:22]: Javadoc would highlight it properly if you write {@code GtfsInput}. Please also put a full stop at the end of the sentence.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/GtfsInputCreationError.java [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+ */
+public class GtfsInputCreationError extends SystemError {
+
+    public GtfsInputCreationError(String exceptionClassName, String message) {
+        super(ImmutableMap.of("exception", exceptionClassName, "message", message));
+    }
+
+    @Override
+    public String getCode() {
+        return "runtime_exception_at_gtfs_input_creation";
```
Comment (aababilov) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/notice/GtfsInputCreationError.java:32]: You are catching IOException, URISyntaxException and InterruptedException and none of them is a runtime exception. I suggest you to create dedicated error classes:

* IOError
* URISyntaxError
* and reuse ThreadInterruptedError.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 5]
```diff
@@ -19,19 +19,21 @@
 import com.beust.jcommander.JCommander;
 import com.google.common.base.Strings;
 import com.google.common.flogger.FluentLogger;
+import org.mobilitydata.gtfsvalidator.input.GtfsFeedName;
```
Comment (aababilov) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:22]: Please revert this formatting change and setup IDEA to use https://github.com/google/google-java-format (see instructions there).

**Review by aababilov — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/IOError.java [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+/** This is related to Input and Output operations in the code. */
+public class IOError extends SystemError {
+
+  public IOError(String message) {
+    super(ImmutableMap.of("message", message));
+  }
+
+  @Override
+  public String getCode() {
+    return "io_exception";
```
Comment (aababilov) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/notice/IOError.java:30]: io_error

File: core/src/main/java/org/mobilitydata/gtfsvalidator/notice/URISyntaxError.java [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+/** Indicates that a string could not be parsed as a URI reference. */
+public class URISyntaxError extends SystemError {
+
+  public URISyntaxError(String message) {
+    super(ImmutableMap.of("message", message));
+  }
+
+  @Override
+  public String getCode() {
+    return "uri_syntax_exception";
```
Comment (aababilov) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/notice/URISyntaxError.java:30]: uri_syntax_error

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 8]
```diff
@@ -75,29 +78,40 @@ public static void main(String[] argv) {
...
-      // FIXME: Add system errors to noticeContainer here.
+      if (e instanceof IOException) {
+        noticeContainer.addSystemError(new IOError(e.getMessage()));
+      }
+      if (e instanceof URISyntaxException) {
+        noticeContainer.addSystemError(new URISyntaxError(e.getMessage()));
+      } else {
+        noticeContainer.addSystemError(new ThreadInterruptedError(e.getMessage()));
+      }
+      exportReport(args.getOutputBase(), noticeContainer);
```
Comment (aababilov) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:89]: Please write separate `catch` sections for each type.

```
} catch (IOException e) {
  logger.atSevere().withCause(e).log("Cannot load GTFS feed");
  noticeContainer.addSystemError(new IOError(e.getMessage()));
} ... {
} ... {
}

if (gtfsInput == null) {
   exportReport(args.getOutputBase(), noticeContainer);
   return;
}
```

**Review by aababilov — CHANGES_REQUESTED** [review]

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java (hunk 8 above)
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:89]: Thanks, I was actually wondering what would be the best practice in this case.

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java [hunk 9]
```diff
@@ -74,30 +77,42 @@ public static void main(String[] argv) {
       } else {
         gtfsInput = GtfsInput.createFromPath(Paths.get(args.getInput()));
       }
-    } catch (IOException | URISyntaxException | InterruptedException e) {
-      // FIXME: Add system errors to noticeContainer here.
+    } catch (IOException e) {
       logger.atSevere().withCause(e).log("Cannot load GTFS feed");
+      noticeContainer.addSystemError(new IOError(e.getMessage()));
+    } catch (URISyntaxException e) {
+      logger.atSevere().withCause(e).log("Syntax error in URL");
```
Comment (barbeau) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java:84]: Nit - if this is catching a `URISyntaxException`, the error message should say `URI` and not `URL`

**Review by barbeau — COMMENTED** [review]
@lionel-nj LGTM! One minor comment

File: main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java (hunk 9 above)
Comment (lionel-nj) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java]: Thanks, I fixed the typo.

**Review by barbeau — APPROVED** [review]
👍 

The semantic bot is hanging for some reason, but all other tests have passed, so I'm going to go ahead and merge.
