### PR TITLE
Fix 1198: separate required column from required value

### LINKED ISSUE #1198: False positives of missing_required_field when encountering empty transfer_type values in transfers.txt
## **Bug report** 

The GTFS Validator is generating false positives of the `missing_required_field` when it encounters empty `transfers.txt#transfer_type` field values.

**Describe the bug**

Given an empty value within the `transfers.txt#transfer_type` field (which is valid [according to the spec](https://gtfs.org/schedule/reference/#:~:text=recommended%20transfer%20point%20between%20routes)), when the validator checks the file, then it will falsely raise a `missing_required_field` notice.

**How we reproduce the bug**

Example feed: [Archive.zip](https://github.com/MobilityData/gtfs-validator/files/9002895/Archive.zip)

In this feed in the `transfers.txt` file, the following use case is shown:

```csv
from_stop_id,to_stop_id,transfer_type,min_transfer_time
1,2,,
```

This is a valid use case in that the `transfer_type` value is empty which indicates a "Recommended transfer point between routes".

**Expected behaviour**

The validator should not flag this as an error.

**Observed behaviour**

The GTFS Validator flagged the above-mentioned use case as an error.

**Screenshots:** 

See relevant JSON output for the above-linked feed.

```json
{
  "notices": [{
    "code": "missing_required_field",
    "severity": "ERROR",
    "totalNotices": 1,
    "sampleNotices": [{
      "filename": "transfers.txt",
      "csvRowNumber": 2.0,
      "fieldName": "transfer_type"
    }]
  },
...
```

**Environment versions**
- validator version: v2, v3.0.1, v3.1.0
- Java version: 
- OS versions:

### PR DESCRIPTION
**Pull request by briandonahue**
**Summary:**

Closes #1198. Added a new annotation `@RequiredColumn` to allow for scenario where a column must exist in the file, but values for that column may be empty.

It may be useful in the future to separate the existing `@Required` annotation into `@RequiredFile` and `@RequiredValue` annotations. I've opened #1343 for discussion of that topic.

**Expected behavior:** 

Given the following `transfers.txt` file, the following should not throw an error:

```
from_stop_id,to_stop_id,transfer_type,min_transfer_time
1,2,,
```

This is a valid use case [according to the spec](https://gtfs.org/schedule/reference/#:~:text=recommended%20transfer%20point%20between%20routes) in that the transfer_type value is empty which indicates a "Recommended transfer point between routes".

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- (N/A) Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by briandonahue** [comment]
@bdferris-v2 As this uses code generation, I was unsure if/how we could add tests for this. Please let me know if you have thoughts.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/RequiredColumn.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ * <p>Example.
+ *
+ * <pre>
+ *   {@literal @}GtfsTable("agency.txt")
+ *   public interface GtfsAgencySchema extends GtfsEntity {
+ *       {@literal @}FieldType(FieldTypeEnum.ID)
+ *       {@literal @}PrimaryKey
+ *       String agencyId();
+ *
+ *       {@literal @}RequiredColumn String agencyName();
```
Comment (bdferris-v2) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/RequiredColumn.java:37]: It might make more sense to use transfers.txt as the example here?

File: core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java [hunk 2]
```diff
@@ -34,16 +34,16 @@ public class DefaultTableHeaderValidator implements TableHeaderValidator {
   public void validate(
       String filename,
       CsvHeader actualHeader,
-      Set<String> supportedColumns,
-      Set<String> requiredColumns,
+      Set<String> supportedHeaders,
+      Set<String> requiredHeaders,
```
Comment (bdferris-v2) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java:38]: Does it make sense to change the naming from "columns" to "headers" when the rest of the method still uses "column" as its naming convention?

**Comment by bdferris-v2** [comment]
Regarding testing, could you introduce a test case in [processor/tests](https://github.com/MobilityData/gtfs-validator/tree/master/processor/tests) with a test schema that exercises the @RequiredColumn behavior?

File: core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java (hunk 2 above)
Comment (briandonahue) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java]: I reverted the change.  I think Header *may* be more accurate as the class is validating headers, but since the notice uses the term "column" and the terms are somewhat mixed and matched, I figured I'd go for consistency in this class.

File: core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Required.java [hunk 3]
```diff
@@ -24,6 +24,8 @@
 /**
  * Adds a validation that the field or a file is required.
  *
+ * <p>In the case of a field, both the column header, and a value for each row is required.
```
Comment (bdferris-v2) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Required.java:27]: nit: remove comma after "column header"

**Review by bdferris-v2 — APPROVED** [review]

**Review by isabelle-dr — APPROVED** [review]

**Comment by isabelle-dr** [comment]
Just a side thought: We have a [missing_required_column](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_required_column) in this validator, and it is triggered when the whole column is missing (as opposed to a missing required field in a given row).
I don't think it necessarily interacts with the work in this PR, just something to keep in mind. 

Merging this PR, thank you @briandonahue!

**Comment by isabelle-dr** [comment]
@briandonahue could you resolve the conflicts? :)

**Comment by briandonahue** [comment]
> @briandonahue could you resolve the conflicts? :)

@isabelle-dr done!

**Comment by isabelle-dr** [comment]
Thank you for this awesome contribution @briandonahue! ✨
