### PR TITLE
Fix #393 - Inverted feed_info.start_date and feed_info.end_date

### LINKED ISSUE #393: [BUG] Inverted feed_info.start_date and feed_info.end_date
**Describe the bug**
1. Said fields are inverted in the notice description 
2. A notice is wrongly generated.

**To Reproduce**
Run the validator on the following dataset: http://data.trilliumtransit.com/gtfs/nts-ca-us/nts-ca-us.zip

**Expected behavior**
No notice should be generated in this case.

**Witnessed behavior**
``Notice{filename='feed_info.txt', level='ERROR', code='39', title='Fields `feed_start_date` and `feed_end_date` out of order', description='`feed_end_date`: `2020-08-12` precedes `feed_start_date`: `2020-12-31` in file `feed_info.txt` for entity with composite id:`feed_publisher_name`: `Trillium Solutions, Inc.` -- `feed_publisher_url`: `http://www.trilliumtransit.com` -- `feed_lang`: `en`.', extra='{compositeKeyFirstPart=feed_publisher_name, compositeKeyThirdPart=feed_lang, compositeKeyThirdValue=en, compositeKeyFirstValue=Trillium Solutions, Inc., compositeKeySecondValue=http://www.trilliumtransit.com, feedInfoStartDate=2020-08-12, compositeKeySecondPart=feed_publisher_url, feedInfoEndDate=2020-12-31}'}]``

**Screenshots**

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: v1.2.2

**Additional context**
External contribution

### PR DESCRIPTION
**Pull request by lionel-nj**
**Summary:**

This PR provides support to correct the bug described in #393: 
-   Rule E037 is wrongly implemented: feed_info.start_date and feed_info.end_date are inverted.

**Expected behavior:** 
- `feed_info.start_date < feed_info.end_date` should not generate a notice.
-  if a notice is generated, field values should not be inverted in the notice description

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

File: usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateFeedInfoEndDateAfterStartDate.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public void execute() {
             final LocalDate feedStartDate = feedInfo.getFeedStartDate();
             final LocalDate feedEndDate = feedInfo.getFeedEndDate();
             if (feedStartDate != null && feedEndDate != null) {
-                if (feedStartDate.isBefore(feedEndDate)) {
+                if (!feedStartDate.isBefore(feedEndDate)) {
```
Comment (fabrice-v) [inline usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateFeedInfoEndDateAfterStartDate.java:64]: Readability is improved by using non inverted logic
```suggestion
                if (feedEndDate.isBefore(feedStartDate)) {
```

**Review by fabrice-v — APPROVED** [review]
LGTM after deinverting the logic and checking that all tests still pass
