### PR TITLE
fix: Feed generates error to authorize upload

### LINKED ISSUE #1562: GTFS download from URL: send a User-Agent
### Describe the problem

As someone hosting (a) GTFS(s), I would like to see in my access logs which and how many requests come from the GTFS Validator, e.g. to gain insights into if/how the feed(s) are being validated, or to provide a more generous bandwidth quota.

### Proposed solution

I propose to let the GTFS Validator send a `User-Agent` header with its requests.

### Alternatives you've considered

_No response_

### Additional context

According to the [`User-Agent` section in RFC 9110 (HTTP Semantics)](https://www.rfc-editor.org/rfc/rfc9110#name-user-agent), `User-Agent` should

> contain[s] information about the user agent originating the request, which is often used by servers to help identify the scope of reported interoperability problems, to work around or tailor responses to avoid particular user agent limitations, and for analytics regarding browser or operating system use. A user agent SHOULD send a User-Agent header field in each request unless specifically configured not to do so.
> […]
> The `User-Agent` field value consists of one or more product identifiers, […], which together identify the user agent software and its significant subproducts. […] Each product identifier consists of a name and optional version.

It is also quite common to include a URL to the software's website or code repository, to let people contact the software's authors more conveniently.

### LINKED ISSUE #1632: Feed generates error to authorize upload
### Describe the bug

When using the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, it generates an "Error authorizing upload". 

### Steps/Code to Reproduce

- Go to Web UI 
- Input https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000 in "Or load from a URL" field 
- Validate feed 
- Generate "Error authorizing upload" error

### Expected Results

Feed generates report successfully. 

### Actual Results

Screenshot 2023-12-19 at 5 58 48 AM

### Screenshots

_No response_

### Files used

_No response_

### Validator version

4.2.0 

### Operating system

MacOS

### Java version

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by davidgamez**
**Summary:**

When using the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, it generates an "Error authorizing upload." While verifying the `invalid_input_files_in_subfolder` notice, an additional request is sent to the producer's URL, causing unexpected behaviors (5XX HTTP code).  This PR reuses the response already loaded in memory, avoiding unnecessary external calls and removing the root cause of the original issue. 
As part of this PR, the GTFS validator is sending the _"User-Agent"_ header with the value _"User-Agent: MobilityData GTFS-Validator/4.2.1 (Java 17.0.6)"_

Fixes #1632 
Closes #1562

How to reproduce the bug:
1. Run the validator locally
2. Input https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000"
3. Validate feed
4. System error is generated with the following format:
```
{
  "notices": [
    {
      "code": "i_o_error",
      "severity": "ERROR",
      "totalNotices": 1,
      "sampleNotices": [
        {
          "exception": "java.io.IOException",
          "message": "Server returned HTTP response code: 503 for URL: https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000"
        }
      ]
    }
  ]
}
```

**Expected behavior:** 

The report is generated without generating system errors.

Screenshot of the validation report after fixed:

Screenshot 2024-01-09 at 5 01 17 PM

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java [hunk 1]
```diff
@@ -171,14 +174,15 @@ public static GtfsInput createFromUrl(
...
+      URL sourceUrl, NoticeContainer noticeContainer, String validatorVersion)
       throws IOException, URISyntaxException {
     try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
-      loadFromUrl(sourceUrl, outputStream);
+      loadFromUrl(sourceUrl, outputStream, validatorVersion);
       File zipFile = new File(sourceUrl.toString());
       String fileName = zipFile.getName().replace(".zip", "");
-      if (hasSubfolderWithGtfsFile(sourceUrl)) {
-
+      if (containsGtfsFileInSubfolder(
```
Comment (jcpitre) [inline core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java:184]: After this change `hasSubfolderWithGtfsFile(sourceUrl)` is not use any more (except in tests). Should we get rid of it?

**Review by jcpitre — APPROVED** [review]
LGTM!

File: core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java (hunk 1 above)
Comment (davidgamez) [reply core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java:172]: Nice catch! Done, Thanks!
