### PR TITLE
fix: Mixed Case false positives

### LINKED ISSUE #1402: False positive mixed_case_recommended_field for numeric values
### Describe the bug

The `mixed_case_recommended_field` warning is always triggered when a field contains digits, like route_short_name=`A1` or trip_short_name=`101`.

Characters which are not letters should not be considered at all when comparing case.

### Steps/Code to Reproduce

Validate a file which uses numbers in fields like `route_short_name` or `trip_short_name`.

### Expected Results

No `mixed_case_recommended_field` warning for those fileds.

### Actual Results

```json
{
      "code": "mixed_case_recommended_field",
      "severity": "WARNING",
      "totalNotices": 360,
      "sampleNotices": [
        {
          "filename": "routes.txt",
          "fieldName": "route_short_name",
          "fieldValue": "A1",
          "csvRowNumber": 2
        },
        {
          "filename": "routes.txt",
          "fieldName": "route_short_name",
          "fieldValue": "ZA12",
          "csvRowNumber": 3
        },
        {
          "filename": "trips.txt",
          "fieldName": "trip_short_name",
          "fieldValue": "301",
          "csvRowNumber": 2
        },
        {
          "filename": "trips.txt",
          "fieldName": "trip_short_name",
          "fieldValue": "5301",
          "csvRowNumber": 3
        },
        {
          "filename": "trips.txt",
          "fieldName": "trip_short_name",
          "fieldValue": "103",
          "csvRowNumber": 4
        },
        ...
}
```

### Screenshots

_No response_

### Files used

https://mkuran.pl/gtfs/wkd.zip

### Validator version

4.1.0

### Operating system

Debian 12

### Java version

openjdk version "17.0.6" 2023-01-17

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by briandonahue**
**Summary:**

Should close #1402.  False positives when warning for Mixed Case values such as when numbers and letters are mixed. 

**Expected behavior:** 

Values with a letter and numbers such as `A102` `302-B` and those with only numbers like `321` should not trigger a warning.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java [hunk 1]
```diff
@@ -70,11 +70,14 @@ private static TypeSpec generateValidator(GtfsFileDescriptor fileDescriptor) {
...
       }
+      String test = "blah";
+
       validateMethod
           .beginControlFlow(
               "if (entity.$L())", FieldNameConverter.hasMethodName(mixedCaseField.name()))
           .addStatement("$T value = entity.$L()", String.class, mixedCaseField.name())
-          .beginControlFlow("if (!(value.matches(\".*[a-z].*\") && value.matches(\".*[A-Z].*\")))")
+          .beginControlFlow(
+              "if (value.matches(\".*\\\\p{L}{2}.*\") && (value.toLowerCase() == value || value.toUpperCase() == value))")
```
Comment (briandonahue) [inline processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java:80]: `\\p{L}{2}` matches any kind of letter from any language, including accented letters and special characters like ç and é.  With this logic, any value with 2 or more consecutive letters will be checked to see if it is all upper or lower case, and add a warning notice if so.  

**Question:** is "2 or more" adequate? The original issue #1402 also had an example value of `ZA12`.  Do we want to try to accommodate values with multiple number/letter combinations or is this adequate since this a warning and not an error?

/cc @isabelle-dr

File: processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/MixedCaseSchemaTest.java [hunk 2]
```diff
@@ -44,29 +53,54 @@ public void setup() throws ValidatorLoaderException {
...
+          {"snake_case", false},
+          {"kebab-case", false},
+          {"UPPER-CASE", false},
+          {"lower case space", false},
+          {"ROUTE 22", false},
+          {"34broadst", false},
+          {"ROUTE 1", false},
+          {"route 1 Boulevard", false},
+          {"Another bad value", false},
+          {"MixedCaseButSingleWord", false},
```
Comment (briandonahue) [inline processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/MixedCaseSchemaTest.java:94]: Feel free to add/suggest more test values.

**Comment by briandonahue** [comment]
@davidgamez I've seen this test fail a few times on different PRs - let me know if there is anything I can do / look for to prevent or fix when this happens.

**Comment by davidgamez** [comment]
> @davidgamez I've seen this test fail a few times on different PRs - let me know if there is anything I can do / look for to prevent or fix when this happens.

Hi @briandonahue I think the test is doing what is expected to do. In this PR, as in others, there are changes made to the notices logic then the threshold of new/dropped notices is greater than 1%. What we can do is review the test results and make sure the changes that we are planning to make sense. You can download the reports and review the example notices.

**Comment by davidgamez** [comment]
@briandonahue I was looking into the acceptance test reports, and it seems that some of the new warnings are coming from the use of full statements in the fields.
Example:

File/field: stop.txt/stop_desc
Value: `Book online or call ... for pickup`. 

@isabelle-dr,  do you think we should trigger the mixed case warning rule in the case of `stop.txt/stop_desc`?

**Comment by isabelle-dr** [comment]
@briandonahue and @davidgamez I am surprised by the acceptance test results in this PR. It has new errors and dropped errors, which is surprising since the mixed case check is a warning. 

Is this because it's out of date with master?

**Comment by isabelle-dr** [comment]
To @davidgamez's question

> do you think we should trigger the mixed case warning rule in the case of stop.txt/stop_desc?

I believe the answer is yes, but I am not entirely sure. @tzujenchanmbd, is `stop_desc` user-facing or is it mostly used between producers and consumers?

**Comment by briandonahue** [comment]
> Is this because it's out of date with master?

**Comment by briandonahue** [comment]
> Is this because it's out of date with master?

@isabelle-dr I merged master and it's still having issues.  I also apparently closed the PR earlier - no idea how I did that... re-opened.

Might need @davidgamez's help with the test errors...

**Comment by davidgamez** [comment]
> To @davidgamez's question
> 
> > do you think we should trigger the mixed case warning rule in the case of stop.txt/stop_desc?
> 
> I believe the answer is yes, but I am not entirely sure. @tzujenchanmbd, is `stop_desc` user-facing or is it mostly used between producers and consumers?

We have sentences in the stop.txt/stop_desc field example: `Book online or call ... for pickup` This implementation looks for every word in the sentence to have mixed cases. This is why we have a lot of new warnings. We have two options;
- Drop the rule for the stop.txt/stop_desc.
- Re-think how the rules behave for sentences.

**Comment by isabelle-dr** [comment]
After a conversation during the contributor meeting, we've decided to go with

> Drop the rule for the stop.txt/stop_desc.

**Comment by isabelle-dr** [comment]
@briandonahue, would you be able to review the acceptance test report to evaluate if this PR removed most of the false positives, or if they still constitute a big portion?

**Review by isabelle-dr — APPROVED** [review]
When we designed the acceptance tests a while back, this is exactly what we had in mind for how it would be useful :)
I had a quick look at the acceptance test report, this change looks good to me, the number of false positives triggered by this notice dropped significantly with the latest changes.

Thank you for the good work @briandonahue and @davidgamez, I am glad we found a way to retain this notice in the validator!

File: processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java [hunk 3]
```diff
@@ -70,18 +70,90 @@ private static TypeSpec generateValidator(GtfsFileDescriptor fileDescriptor) {
...
           .addStatement(
               "noticeContainer.addValidationNotice(new $T(\"$L\", \"$L\", value, entity.csvRowNumber()))",
               MixedCaseRecommendedFieldNotice.class,
               fileDescriptor.filename(),
               FieldNameConverter.gtfsColumnName(mixedCaseField.name()))
           .endControlFlow()
+          .endControlFlow()
           .endControlFlow();
+
+      //      validateMethod
```
Comment (davidgamez) [inline processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java:118]: Please remove the commented code before merging.

File: processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java [hunk 4]
```diff
@@ -70,18 +70,90 @@ private static TypeSpec generateValidator(GtfsFileDescriptor fileDescriptor) {
       if (!mixedCaseField.mixedCase()) {
         continue;
       }
+      String test = "blah";
```
Comment (davidgamez) [inline processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java:73]: This is probably a left over from testing/debugging the class; please delete the line.

**Review by davidgamez — APPROVED** [review]
