### PR TITLE
fix: fix OutOfBoundsException when agency.txt is missing in the input data…

### LINKED ISSUE #1538: Runtime exception in validator: java.lang.IndexOutOfBoundsException
### Describe the bug

Jul. 11, 2023 4:31:20 P.M. org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader loadAndValidate
INFO: Loading in 1 threads
Jul. 11, 2023 4:31:20 P.M. org.mobilitydata.gtfsvalidator.validator.ValidatorUtil safeValidate
SEVERE: Runtime exception in validator org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator.validate(AgencyConsistencyValidator.java:83)
	at org.mobilitydata.gtfsvalidator.validator.ValidatorUtil.safeValidate(ValidatorUtil.java:74)
	at org.mobilitydata.gtfsvalidator.validator.ValidatorUtil.invokeSingleFileValidators(ValidatorUtil.java:55)
	at org.mobilitydata.gtfsvalidator.table.AnyTableLoader.loadMissingFile(AnyTableLoader.java:196)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.loadAndValidate(GtfsFeedLoader.java:131)
	at org.mobilitydata.gtfsvalidator.runner.ValidationRunner.loadAndValidate(ValidationRunner.java:204)
	at org.mobilitydata.gtfsvalidator.runner.ValidationRunner.run(ValidationRunner.java:122)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:68)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### Steps/Code to Reproduce

- Run the following command:
java -Xmx1G -jar ./cli/build/libs/gtfs-validator-4.1.1-SNAPSHOT-cli.jar -o ~/code/data/gtfs-ws/delfi -i /Users/jingsi/Downloads/winzip.zip

### Expected Results

No java.lang.IndexOutOfBoundsException

### Actual Results

SEVERE: Runtime exception in validator org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### Screenshots

_No response_

### Files used

_No response_

### Validator version

v4.1.1

### Operating system

MacOS

### Java version

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
…set where agencyCount == 0

**Summary:**
Closes #1538 
Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java [hunk 1]
```diff
@@ -78,17 +78,18 @@ public void validate(NoticeContainer noticeContainer) {
...
+      for (int i = 1; i < agencyCount; ++i) {
+        GtfsAgency agency = agencyTable.getEntities().get(i);
+        if (!commonTimezone.equals(agency.agencyTimezone())) {
+          noticeContainer.addValidationNotice(
+              new InconsistentAgencyTimezoneNotice(
+                  agency.csvRowNumber(), commonTimezone.getId(), agency.agencyTimezone().getId()));
+        }
       }
     }
+
```
Comment (cka-y) [inline main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java:92]: I don't see any difference here? is it just white space?

**Review by cka-y — APPROVED** [review]
LGTM

File: main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java (hunk 1 above)
Comment (davidgamez) [reply main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java:92]: It looks like a new line.
