### PR TITLE
fix: Added a execution result file

### LINKED ISSUE #1688: Create execution_result.json file for web validator jobs
# Description

Modify the web validator validate endpoint, creating  execution_result.json when an exception is thrown or the validation process completes successfully.

```
"status": "",
"error": "Error...."
```

Related to: #1651

### PR DESCRIPTION
**Pull request by jcpitre**
**Summary:**

closes #1688

Added `execution_result.json` file containing the result of the execution of the validation.
This file should be available at the same location as the report files (report.html, report.json, etc)
Typical contents of this file:
```
{
  "status": "error",
  "error": "Validation failed"
}
``` 
or
```
{
  "status": "success",
  "error": ""
}
```

Now the endpoint always return 200.

**Testing tips**

- Deploy to staging
   - I added a manual trigger to `.github/workflows/stg_web_svc_merge.yml` but this will not be available until this branch is merged into master.
   - Meanwhile you can create your own branch and add a push to your branch trigger
   - You don't need to deploy the client.
- On the staging client web page, select a good dataset and validate it. Open the report.
- Replace `report.html` at the end of the report URL by `execution_result.json`. You should be able to load the file
- Try gain with a broken dataset

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java [hunk 1]
```diff
@@ -93,27 +100,38 @@ public ResponseEntity runValidator(
...
       Sentry.captureException(exc);
-      throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Error", exc);
+      logger.info("Validation failed. Writing " + executionResultFile + " file");
+      new ExecutionResult("error", exc.getMessage()).writeToFile(outputPath);
+      try {
+        // There was a failure but we still try to upload the execution_result file.
+        storageHelper.uploadFilesToStorage(jobId, outputPath);
+      } catch (IOException e) {
+        logger.error("Error: Could not upload to file storage", e);
+      }
```
Comment (davidgamez) [inline web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java:132]: We should look into the scenario where _storageHelper.uploadFilesToStorage_ throws an exception. The uploadFilesToStorage depends on network and Storage reliability; failures should be temporary rather than permanent. This implementation will not upload the file or retry the event's processing. In this case, let the GCP retry as it might be fixed the previous. Otherwise, the consumer will keep waiting for a file that will never appear. To handle this scenario we can move the _storageHelper.uploadFilesToStorage(jobId, outputPath);_ to the finally block

Comment (jcpitre) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java:132]: It's like nobody throws specific exceptions these days. I will have to discriminate by having separate try-catch for storage and for validation.

Comment (davidgamez) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java:132]: Sorry, I was also suggesting that all _storageHelper.uploadFilesToStorage_ calls should move to the finally block, but I wasn't explicit enough  :-(

File: web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java [hunk 2]
```diff
@@ -125,6 +143,35 @@ public ResponseEntity runValidator(
...
+    private String status;
+    private String error;
+
+    // Constructor
+    public ExecutionResult(String status, String error) {
+      this.status = status;
+      this.error = error;
+    }
+
+    public void writeToFile(Path outputPath) {
```
[the remark this answers is not in the document]
Comment (jcpitre) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java:156]: StorageHelper is specific about interacting with GCS, whereas there's nothing of GCS in that method.

[the remark this answers is not in the document]
Comment (davidgamez) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java:156]: Regardless of the comment from the class, the StorageHelper class contains methods that are not 100% related to GCS. I suggested moving it to that class to keep the ExecutionResult clean and agnostic of its use.

[the remark this answers is not in the document]
Comment (jcpitre) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java]: Done

File: web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java (hunk 1 above)
Comment (jcpitre) [reply web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java]: I went for a slightly different option. Essentially any error within the validator will return 200 and fill the execution result file. Any error not in the validator (which includes all error related to storage) will return 500 and trigger a retry.

**Review by qcdyx — APPROVED** [review]
LGTM

**Review by davidgamez — APPROVED** [review]
